### PR TITLE
Add bitcoin testnet support

### PR DESCRIPTION
**Pull request by pkova**
Working on  various parts of the bitcoin wallet two problems came up with my stuff from #92.

1) We need bitcoin testnet support.
2) The default output key format required unnecessary, duplicated and error prone massaging in both Bridge and our BTC Wallet. It's better to do it here, so instead of outputting `keys: {public, private, chain, address}` we now output `keys:{xpub, xprv}`.

This PR addresses both problems.

### CODE REVIEW

**Review by jtobin — APPROVED** [review]
LGTM, I'll merge unless anyone has any qualms.

**Comment by pkova** [comment]
Yo @jtobin, release this to npm when you got the time.

**Comment by jtobin** [comment]
Done!

**Comment by Fang-** [comment]
@pkova looks like updating Bridge to work with this isn't entirely trivial a task (key transformation shenanigans involved). Humbly requesting that you do a matching Bridge PR when you have the time. Thank you! (:

**Pull request merged**
